// Generated by rstantools.  Do not edit by hand.

/*
    muvamere is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    muvamere is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with muvamere.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_mvn_inferH_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 71> locations_array__ =
  {" (found before start of program)",
  " (in 'mvn_inferH', line 22, column 2 to column 40)",
  " (in 'mvn_inferH', line 23, column 2 to column 31)",
  " (in 'mvn_inferH', line 24, column 2 to column 36)",
  " (in 'mvn_inferH', line 25, column 2 to column 32)",
  " (in 'mvn_inferH', line 26, column 2 to column 22)",
  " (in 'mvn_inferH', line 27, column 2 to column 31)",
  " (in 'mvn_inferH', line 28, column 2 to column 27)",
  " (in 'mvn_inferH', line 29, column 2 to column 27)",
  " (in 'mvn_inferH', line 30, column 2 to column 28)",
  " (in 'mvn_inferH', line 33, column 2 to column 25)",
  " (in 'mvn_inferH', line 34, column 2 to column 31)",
  " (in 'mvn_inferH', line 36, column 4 to column 84)",
  " (in 'mvn_inferH', line 35, column 22 to line 37, column 3)",
  " (in 'mvn_inferH', line 35, column 2 to line 37, column 3)",
  " (in 'mvn_inferH', line 39, column 4 to column 35)",
  " (in 'mvn_inferH', line 38, column 22 to line 40, column 3)",
  " (in 'mvn_inferH', line 38, column 2 to line 40, column 3)",
  " (in 'mvn_inferH', line 44, column 2 to column 50)",
  " (in 'mvn_inferH', line 45, column 2 to column 25)",
  " (in 'mvn_inferH', line 46, column 2 to column 34)",
  " (in 'mvn_inferH', line 47, column 2 to column 34)",
  " (in 'mvn_inferH', line 48, column 2 to column 47)",
  " (in 'mvn_inferH', line 49, column 2 to column 47)",
  " (in 'mvn_inferH', line 52, column 4 to column 31)",
  " (in 'mvn_inferH', line 53, column 4 to column 53)",
  " (in 'mvn_inferH', line 54, column 4 to column 68)",
  " (in 'mvn_inferH', line 51, column 22 to line 55, column 3)",
  " (in 'mvn_inferH', line 51, column 2 to line 55, column 3)",
  " (in 'mvn_inferH', line 58, column 4 to column 46)",
  " (in 'mvn_inferH', line 57, column 22 to line 59, column 3)",
  " (in 'mvn_inferH', line 57, column 2 to line 59, column 3)",
  " (in 'mvn_inferH', line 2, column 2 to column 15)",
  " (in 'mvn_inferH', line 3, column 2 to column 15)",
  " (in 'mvn_inferH', line 4, column 12 to column 20)",
  " (in 'mvn_inferH', line 4, column 2 to column 22)",
  " (in 'mvn_inferH', line 5, column 2 to column 9)",
  " (in 'mvn_inferH', line 6, column 2 to column 9)",
  " (in 'mvn_inferH', line 7, column 9 to column 17)",
  " (in 'mvn_inferH', line 7, column 18 to column 20)",
  " (in 'mvn_inferH', line 7, column 2 to column 24)",
  " (in 'mvn_inferH', line 8, column 9 to column 17)",
  " (in 'mvn_inferH', line 8, column 18 to column 20)",
  " (in 'mvn_inferH', line 8, column 2 to column 24)",
  " (in 'mvn_inferH', line 9, column 2 to column 22)",
  " (in 'mvn_inferH', line 10, column 2 to column 22)",
  " (in 'mvn_inferH', line 11, column 2 to column 21)",
  " (in 'mvn_inferH', line 12, column 2 to column 21)",
  " (in 'mvn_inferH', line 13, column 2 to column 29)",
  " (in 'mvn_inferH', line 14, column 2 to column 30)",
  " (in 'mvn_inferH', line 15, column 2 to column 12)",
  " (in 'mvn_inferH', line 16, column 2 to column 12)",
  " (in 'mvn_inferH', line 22, column 30 to column 38)",
  " (in 'mvn_inferH', line 22, column 14 to column 16)",
  " (in 'mvn_inferH', line 23, column 14 to column 16)",
  " (in 'mvn_inferH', line 24, column 26 to column 34)",
  " (in 'mvn_inferH', line 24, column 18 to column 20)",
  " (in 'mvn_inferH', line 25, column 22 to column 30)",
  " (in 'mvn_inferH', line 25, column 9 to column 11)",
  " (in 'mvn_inferH', line 25, column 12 to column 14)",
  " (in 'mvn_inferH', line 26, column 9 to column 11)",
  " (in 'mvn_inferH', line 26, column 12 to column 14)",
  " (in 'mvn_inferH', line 27, column 18 to column 20)",
  " (in 'mvn_inferH', line 27, column 21 to column 23)",
  " (in 'mvn_inferH', line 28, column 18 to column 20)",
  " (in 'mvn_inferH', line 29, column 18 to column 20)",
  " (in 'mvn_inferH', line 33, column 9 to column 17)",
  " (in 'mvn_inferH', line 33, column 18 to column 20)",
  " (in 'mvn_inferH', line 34, column 21 to column 29)",
  " (in 'mvn_inferH', line 34, column 9 to column 11)",
  " (in 'mvn_inferH', line 34, column 12 to column 14)"};
#include <stan_meta_header.hpp>
class model_mvn_inferH final : public model_base_crtp<model_mvn_inferH> {
private:
  int Nrecords;
  int Nstudies;
  std::vector<int> study;
  int NP;
  int NV;
  Eigen::Matrix<double,-1,-1> X_data__;
  Eigen::Matrix<double,-1,-1> Y_data__;
  double betaM_prior_sd;
  double betaS_prior_sd;
  double tauM_prior_sd;
  double tauS_prior_sd;
  double lkj_local_prior_scale;
  double lkj_global_prior_scale;
  double rhoA;
  double rhoB;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Y{nullptr, 0, 0};
public:
  ~model_mvn_inferH() {}
  model_mvn_inferH(stan::io::var_context& context__, unsigned int
                   random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_mvn_inferH_namespace::model_mvn_inferH";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 32;
      context__.validate_dims("data initialization", "Nrecords", "int",
        std::vector<size_t>{});
      Nrecords = std::numeric_limits<int>::min();
      current_statement__ = 32;
      Nrecords = context__.vals_i("Nrecords")[(1 - 1)];
      current_statement__ = 33;
      context__.validate_dims("data initialization", "Nstudies", "int",
        std::vector<size_t>{});
      Nstudies = std::numeric_limits<int>::min();
      current_statement__ = 33;
      Nstudies = context__.vals_i("Nstudies")[(1 - 1)];
      current_statement__ = 34;
      stan::math::validate_non_negative_index("study", "Nrecords", Nrecords);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "study", "int",
        std::vector<size_t>{static_cast<size_t>(Nrecords)});
      study = std::vector<int>(Nrecords, std::numeric_limits<int>::min());
      current_statement__ = 35;
      study = context__.vals_i("study");
      current_statement__ = 36;
      context__.validate_dims("data initialization", "NP", "int",
        std::vector<size_t>{});
      NP = std::numeric_limits<int>::min();
      current_statement__ = 36;
      NP = context__.vals_i("NP")[(1 - 1)];
      current_statement__ = 37;
      context__.validate_dims("data initialization", "NV", "int",
        std::vector<size_t>{});
      NV = std::numeric_limits<int>::min();
      current_statement__ = 37;
      NV = context__.vals_i("NV")[(1 - 1)];
      current_statement__ = 38;
      stan::math::validate_non_negative_index("X", "Nrecords", Nrecords);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("X", "NP", NP);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(Nrecords),
          static_cast<size_t>(NP)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(Nrecords, NP,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(),
        Nrecords, NP);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 40;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 40;
        pos__ = 1;
        current_statement__ = 40;
        for (int sym1__ = 1; sym1__ <= NP; ++sym1__) {
          current_statement__ = 40;
          for (int sym2__ = 1; sym2__ <= Nrecords; ++sym2__) {
            current_statement__ = 40;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 40;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 41;
      stan::math::validate_non_negative_index("Y", "Nrecords", Nrecords);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("Y", "NV", NV);
      current_statement__ = 43;
      context__.validate_dims("data initialization", "Y", "double",
        std::vector<size_t>{static_cast<size_t>(Nrecords),
          static_cast<size_t>(NV)});
      Y_data__ = Eigen::Matrix<double,-1,-1>::Constant(Nrecords, NV,
                   std::numeric_limits<double>::quiet_NaN());
      new (&Y) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Y_data__.data(),
        Nrecords, NV);
      {
        std::vector<local_scalar_t__> Y_flat__;
        current_statement__ = 43;
        Y_flat__ = context__.vals_r("Y");
        current_statement__ = 43;
        pos__ = 1;
        current_statement__ = 43;
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          current_statement__ = 43;
          for (int sym2__ = 1; sym2__ <= Nrecords; ++sym2__) {
            current_statement__ = 43;
            stan::model::assign(Y, Y_flat__[(pos__ - 1)],
              "assigning variable Y", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 43;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 44;
      context__.validate_dims("data initialization", "betaM_prior_sd",
        "double", std::vector<size_t>{});
      betaM_prior_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 44;
      betaM_prior_sd = context__.vals_r("betaM_prior_sd")[(1 - 1)];
      current_statement__ = 45;
      context__.validate_dims("data initialization", "betaS_prior_sd",
        "double", std::vector<size_t>{});
      betaS_prior_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 45;
      betaS_prior_sd = context__.vals_r("betaS_prior_sd")[(1 - 1)];
      current_statement__ = 46;
      context__.validate_dims("data initialization", "tauM_prior_sd",
        "double", std::vector<size_t>{});
      tauM_prior_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 46;
      tauM_prior_sd = context__.vals_r("tauM_prior_sd")[(1 - 1)];
      current_statement__ = 47;
      context__.validate_dims("data initialization", "tauS_prior_sd",
        "double", std::vector<size_t>{});
      tauS_prior_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 47;
      tauS_prior_sd = context__.vals_r("tauS_prior_sd")[(1 - 1)];
      current_statement__ = 48;
      context__.validate_dims("data initialization", "lkj_local_prior_scale",
        "double", std::vector<size_t>{});
      lkj_local_prior_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 48;
      lkj_local_prior_scale = context__.vals_r("lkj_local_prior_scale")[(1 -
        1)];
      current_statement__ = 49;
      context__.validate_dims("data initialization",
        "lkj_global_prior_scale", "double", std::vector<size_t>{});
      lkj_global_prior_scale = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 49;
      lkj_global_prior_scale = context__.vals_r("lkj_global_prior_scale")[(1
        - 1)];
      current_statement__ = 50;
      context__.validate_dims("data initialization", "rhoA", "double",
        std::vector<size_t>{});
      rhoA = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 50;
      rhoA = context__.vals_r("rhoA")[(1 - 1)];
      current_statement__ = 51;
      context__.validate_dims("data initialization", "rhoB", "double",
        std::vector<size_t>{});
      rhoB = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 51;
      rhoB = context__.vals_r("rhoB")[(1 - 1)];
      current_statement__ = 52;
      stan::math::validate_non_negative_index("Omega_local", "Nstudies",
        Nstudies);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("Omega_local", "NV", NV);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("Omega_local", "NV", NV);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("Omega_global", "NV", NV);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("Omega_global", "NV", NV);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("tau", "Nstudies", Nstudies);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("tau", "NV", NV);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("Betas", "Nstudies", Nstudies);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("Betas", "NP", NP);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("Betas", "NV", NV);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("BetaM", "NP", NP);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("BetaM", "NV", NV);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("BetaS", "NP", NP);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("BetaS", "NV", NV);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("taum", "NV", NV);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("sigt", "NV", NV);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("mu", "Nrecords", Nrecords);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("mu", "NV", NV);
      current_statement__ = 68;
      stan::math::validate_non_negative_index("Sigs", "Nstudies", Nstudies);
      current_statement__ = 69;
      stan::math::validate_non_negative_index("Sigs", "NV", NV);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("Sigs", "NV", NV);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (Nstudies * ((NV * (NV - 1)) / 2)) + ((NV * (NV - 1)) /
      2) + (Nstudies * NV) + (Nstudies * NP * NV) + (NP * NV) + (NP * NV) +
      NV + NV + 1;
  }
  inline std::string model_name() const final {
    return "model_mvn_inferH";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_mvn_inferH_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> Omega_local =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NV, NV,
            DUMMY_VAR__));
      current_statement__ = 1;
      Omega_local = in__.template read_constrain_corr_matrix<
                      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>,
                      jacobian__>(lp__, Nstudies, NV);
      Eigen::Matrix<local_scalar_t__,-1,-1> Omega_global =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NV, NV, DUMMY_VAR__);
      current_statement__ = 2;
      Omega_global = in__.template read_constrain_corr_matrix<
                       Eigen::Matrix<local_scalar_t__,-1,-1>,
                       jacobian__>(lp__, NV);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> tau =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NV, DUMMY_VAR__));
      current_statement__ = 3;
      tau = in__.template read_constrain_lb<
              std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
              jacobian__>(0, lp__, Nstudies, NV);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> Betas =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NP, NV,
            DUMMY_VAR__));
      current_statement__ = 4;
      Betas = in__.template read<
                std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(Nstudies,
                NP, NV);
      Eigen::Matrix<local_scalar_t__,-1,-1> BetaM =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NP, NV, DUMMY_VAR__);
      current_statement__ = 5;
      BetaM = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(NP,
                NV);
      Eigen::Matrix<local_scalar_t__,-1,-1> BetaS =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NP, NV, DUMMY_VAR__);
      current_statement__ = 6;
      BetaS = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(0, lp__,
                NP, NV);
      Eigen::Matrix<local_scalar_t__,-1,1> taum =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NV, DUMMY_VAR__);
      current_statement__ = 7;
      taum = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, NV);
      Eigen::Matrix<local_scalar_t__,-1,1> sigt =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NV, DUMMY_VAR__);
      current_statement__ = 8;
      sigt = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, NV);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 9;
      rho = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<local_scalar_t__,-1,-1> mu =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(Nrecords, NV,
          DUMMY_VAR__);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> Sigs =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NV, NV,
            DUMMY_VAR__));
      current_statement__ = 14;
      for (int i = 1; i <= Nstudies; ++i) {
        current_statement__ = 12;
        stan::model::assign(Sigs,
          stan::math::quad_form_diag(
            stan::math::add(stan::math::multiply(rho, Omega_global),
              stan::math::multiply((1 - rho),
                stan::model::rvalue(Omega_local, "Omega_local",
                  stan::model::index_uni(i)))),
            stan::model::rvalue(tau, "tau", stan::model::index_uni(i))),
          "assigning variable Sigs", stan::model::index_uni(i));
      }
      current_statement__ = 17;
      for (int n = 1; n <= Nrecords; ++n) {
        current_statement__ = 15;
        stan::model::assign(mu,
          stan::math::multiply(
            stan::model::rvalue(X, "X", stan::model::index_uni(n)),
            stan::model::rvalue(Betas, "Betas",
              stan::model::index_uni(
                stan::model::rvalue(study, "study", stan::model::index_uni(n))))),
          "assigning variable mu", stan::model::index_uni(n));
      }
      {
        current_statement__ = 18;
        lp_accum__.add(stan::math::lkj_corr_lpdf<propto__>(Omega_global,
                         lkj_global_prior_scale));
        current_statement__ = 19;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(rho, rhoA, rhoB));
        current_statement__ = 20;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(taum, 0,
                         tauM_prior_sd));
        current_statement__ = 21;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigt, 0,
                         tauS_prior_sd));
        current_statement__ = 22;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::math::to_vector(BetaM), 0, betaM_prior_sd));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(
                         stan::math::to_vector(BetaS), 0, betaS_prior_sd));
        current_statement__ = 28;
        for (int i = 1; i <= Nstudies; ++i) {
          current_statement__ = 24;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(tau, "tau",
                             stan::model::index_uni(i)), taum, sigt));
          current_statement__ = 25;
          lp_accum__.add(stan::math::lkj_corr_lpdf<propto__>(
                           stan::model::rvalue(Omega_local, "Omega_local",
                             stan::model::index_uni(i)),
                           lkj_local_prior_scale));
          current_statement__ = 26;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::math::to_vector(
                             stan::model::rvalue(Betas, "Betas",
                               stan::model::index_uni(i))),
                           stan::math::to_vector(BetaM),
                           stan::math::to_vector(BetaS)));
        }
        current_statement__ = 31;
        for (int n = 1; n <= Nrecords; ++n) {
          current_statement__ = 29;
          lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(
                           stan::model::rvalue(Y, "Y",
                             stan::model::index_uni(n)),
                           stan::model::rvalue(mu, "mu",
                             stan::model::index_uni(n)),
                           stan::model::rvalue(Sigs, "Sigs",
                             stan::model::index_uni(
                               stan::model::rvalue(study, "study",
                                 stan::model::index_uni(n))))));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_mvn_inferH_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<Eigen::Matrix<double,-1,-1>> Omega_local =
        std::vector<Eigen::Matrix<double,-1,-1>>(Nstudies,
          Eigen::Matrix<double,-1,-1>::Constant(NV, NV,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 1;
      Omega_local = in__.template read_constrain_corr_matrix<
                      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>,
                      jacobian__>(lp__, Nstudies, NV);
      Eigen::Matrix<double,-1,-1> Omega_global =
        Eigen::Matrix<double,-1,-1>::Constant(NV, NV,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      Omega_global = in__.template read_constrain_corr_matrix<
                       Eigen::Matrix<local_scalar_t__,-1,-1>,
                       jacobian__>(lp__, NV);
      std::vector<Eigen::Matrix<double,-1,1>> tau =
        std::vector<Eigen::Matrix<double,-1,1>>(Nstudies,
          Eigen::Matrix<double,-1,1>::Constant(NV,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 3;
      tau = in__.template read_constrain_lb<
              std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>,
              jacobian__>(0, lp__, Nstudies, NV);
      std::vector<Eigen::Matrix<double,-1,-1>> Betas =
        std::vector<Eigen::Matrix<double,-1,-1>>(Nstudies,
          Eigen::Matrix<double,-1,-1>::Constant(NP, NV,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 4;
      Betas = in__.template read<
                std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>>(Nstudies,
                NP, NV);
      Eigen::Matrix<double,-1,-1> BetaM =
        Eigen::Matrix<double,-1,-1>::Constant(NP, NV,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 5;
      BetaM = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(NP,
                NV);
      Eigen::Matrix<double,-1,-1> BetaS =
        Eigen::Matrix<double,-1,-1>::Constant(NP, NV,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      BetaS = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(0, lp__,
                NP, NV);
      Eigen::Matrix<double,-1,1> taum =
        Eigen::Matrix<double,-1,1>::Constant(NV,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      taum = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, NV);
      Eigen::Matrix<double,-1,1> sigt =
        Eigen::Matrix<double,-1,1>::Constant(NV,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 8;
      sigt = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, NV);
      double rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 9;
      rho = in__.template read_constrain_lub<local_scalar_t__, jacobian__>(0,
              1, lp__);
      Eigen::Matrix<double,-1,-1> mu =
        Eigen::Matrix<double,-1,-1>::Constant(Nrecords, NV,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<Eigen::Matrix<double,-1,-1>> Sigs =
        std::vector<Eigen::Matrix<double,-1,-1>>(Nstudies,
          Eigen::Matrix<double,-1,-1>::Constant(NV, NV,
            std::numeric_limits<double>::quiet_NaN()));
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= NV; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
            out__.write(stan::model::rvalue(Omega_local, "Omega_local",
                          stan::model::index_uni(sym3__),
                          stan::model::index_uni(sym2__),
                          stan::model::index_uni(sym1__)));
          }
        }
      }
      out__.write(Omega_global);
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= Nstudies; ++sym2__) {
          out__.write(tau[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
            out__.write(stan::model::rvalue(Betas, "Betas",
                          stan::model::index_uni(sym3__),
                          stan::model::index_uni(sym2__),
                          stan::model::index_uni(sym1__)));
          }
        }
      }
      out__.write(BetaM);
      out__.write(BetaS);
      out__.write(taum);
      out__.write(sigt);
      out__.write(rho);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 14;
      for (int i = 1; i <= Nstudies; ++i) {
        current_statement__ = 12;
        stan::model::assign(Sigs,
          stan::math::quad_form_diag(
            stan::math::add(stan::math::multiply(rho, Omega_global),
              stan::math::multiply((1 - rho),
                stan::model::rvalue(Omega_local, "Omega_local",
                  stan::model::index_uni(i)))),
            stan::model::rvalue(tau, "tau", stan::model::index_uni(i))),
          "assigning variable Sigs", stan::model::index_uni(i));
      }
      current_statement__ = 17;
      for (int n = 1; n <= Nrecords; ++n) {
        current_statement__ = 15;
        stan::model::assign(mu,
          stan::math::multiply(
            stan::model::rvalue(X, "X", stan::model::index_uni(n)),
            stan::model::rvalue(Betas, "Betas",
              stan::model::index_uni(
                stan::model::rvalue(study, "study", stan::model::index_uni(n))))),
          "assigning variable mu", stan::model::index_uni(n));
      }
      if (emit_transformed_parameters__) {
        out__.write(mu);
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= NV; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
              out__.write(stan::model::rvalue(Sigs, "Sigs",
                            stan::model::index_uni(sym3__),
                            stan::model::index_uni(sym2__),
                            stan::model::index_uni(sym1__)));
            }
          }
        }
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> Omega_local =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NV, NV,
            DUMMY_VAR__));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        current_statement__ = 1;
        for (int sym2__ = 1; sym2__ <= NV; ++sym2__) {
          current_statement__ = 1;
          for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
            current_statement__ = 1;
            stan::model::assign(Omega_local, in__.read<local_scalar_t__>(),
              "assigning variable Omega_local",
              stan::model::index_uni(sym3__), stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write_free_corr_matrix(Omega_local);
      Eigen::Matrix<local_scalar_t__,-1,-1> Omega_global =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NV, NV, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(Omega_global,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(NV, NV),
        "assigning variable Omega_global");
      out__.write_free_corr_matrix(Omega_global);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> tau =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NV, DUMMY_VAR__));
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        current_statement__ = 3;
        for (int sym2__ = 1; sym2__ <= Nstudies; ++sym2__) {
          current_statement__ = 3;
          stan::model::assign(tau, in__.read<local_scalar_t__>(),
            "assigning variable tau", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write_free_lb(0, tau);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> Betas =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NP, NV,
            DUMMY_VAR__));
      current_statement__ = 4;
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        current_statement__ = 4;
        for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
          current_statement__ = 4;
          for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
            current_statement__ = 4;
            stan::model::assign(Betas, in__.read<local_scalar_t__>(),
              "assigning variable Betas", stan::model::index_uni(sym3__),
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write(Betas);
      Eigen::Matrix<local_scalar_t__,-1,-1> BetaM =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NP, NV, DUMMY_VAR__);
      current_statement__ = 5;
      stan::model::assign(BetaM,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(NP, NV),
        "assigning variable BetaM");
      out__.write(BetaM);
      Eigen::Matrix<local_scalar_t__,-1,-1> BetaS =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NP, NV, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(BetaS,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(NP, NV),
        "assigning variable BetaS");
      out__.write_free_lb(0, BetaS);
      Eigen::Matrix<local_scalar_t__,-1,1> taum =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NV, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(taum,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(NV),
        "assigning variable taum");
      out__.write_free_lb(0, taum);
      Eigen::Matrix<local_scalar_t__,-1,1> sigt =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NV, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(sigt,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(NV),
        "assigning variable sigt");
      out__.write_free_lb(0, sigt);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 9;
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, rho);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "Omega_local",
        "double",
        std::vector<size_t>{static_cast<size_t>(Nstudies),
          static_cast<size_t>(NV), static_cast<size_t>(NV)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "Omega_global",
        "double",
        std::vector<size_t>{static_cast<size_t>(NV), static_cast<size_t>(NV)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "tau", "double",
        std::vector<size_t>{static_cast<size_t>(Nstudies),
          static_cast<size_t>(NV)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "Betas", "double",
        std::vector<size_t>{static_cast<size_t>(Nstudies),
          static_cast<size_t>(NP), static_cast<size_t>(NV)});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "BetaM", "double",
        std::vector<size_t>{static_cast<size_t>(NP), static_cast<size_t>(NV)});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "BetaS", "double",
        std::vector<size_t>{static_cast<size_t>(NP), static_cast<size_t>(NV)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "taum", "double",
        std::vector<size_t>{static_cast<size_t>(NV)});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization", "sigt", "double",
        std::vector<size_t>{static_cast<size_t>(NV)});
      current_statement__ = 9;
      context__.validate_dims("parameter initialization", "rho", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> Omega_local =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NV, NV,
            DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> Omega_local_flat__;
        current_statement__ = 1;
        Omega_local_flat__ = context__.vals_r("Omega_local");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= NV; ++sym2__) {
            current_statement__ = 1;
            for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
              current_statement__ = 1;
              stan::model::assign(Omega_local, Omega_local_flat__[(pos__ -
                1)], "assigning variable Omega_local",
                stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 1;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write_free_corr_matrix(Omega_local);
      Eigen::Matrix<local_scalar_t__,-1,-1> Omega_global =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NV, NV, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> Omega_global_flat__;
        current_statement__ = 2;
        Omega_global_flat__ = context__.vals_r("Omega_global");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= NV; ++sym2__) {
            current_statement__ = 2;
            stan::model::assign(Omega_global, Omega_global_flat__[(pos__ -
              1)], "assigning variable Omega_global",
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
            current_statement__ = 2;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_corr_matrix(Omega_global);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> tau =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NV, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> tau_flat__;
        current_statement__ = 3;
        tau_flat__ = context__.vals_r("tau");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= Nstudies; ++sym2__) {
            current_statement__ = 3;
            stan::model::assign(tau, tau_flat__[(pos__ - 1)],
              "assigning variable tau", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 3;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lb(0, tau);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> Betas =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(Nstudies,
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NP, NV,
            DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> Betas_flat__;
        current_statement__ = 4;
        Betas_flat__ = context__.vals_r("Betas");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          current_statement__ = 4;
          for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
            current_statement__ = 4;
            for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
              current_statement__ = 4;
              stan::model::assign(Betas, Betas_flat__[(pos__ - 1)],
                "assigning variable Betas", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              current_statement__ = 4;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write(Betas);
      Eigen::Matrix<local_scalar_t__,-1,-1> BetaM =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NP, NV, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> BetaM_flat__;
        current_statement__ = 5;
        BetaM_flat__ = context__.vals_r("BetaM");
        current_statement__ = 5;
        pos__ = 1;
        current_statement__ = 5;
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          current_statement__ = 5;
          for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
            current_statement__ = 5;
            stan::model::assign(BetaM, BetaM_flat__[(pos__ - 1)],
              "assigning variable BetaM", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 5;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(BetaM);
      Eigen::Matrix<local_scalar_t__,-1,-1> BetaS =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(NP, NV, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> BetaS_flat__;
        current_statement__ = 6;
        BetaS_flat__ = context__.vals_r("BetaS");
        current_statement__ = 6;
        pos__ = 1;
        current_statement__ = 6;
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          current_statement__ = 6;
          for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
            current_statement__ = 6;
            stan::model::assign(BetaS, BetaS_flat__[(pos__ - 1)],
              "assigning variable BetaS", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 6;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_lb(0, BetaS);
      Eigen::Matrix<local_scalar_t__,-1,1> taum =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NV, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> taum_flat__;
        current_statement__ = 7;
        taum_flat__ = context__.vals_r("taum");
        current_statement__ = 7;
        pos__ = 1;
        current_statement__ = 7;
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          current_statement__ = 7;
          stan::model::assign(taum, taum_flat__[(pos__ - 1)],
            "assigning variable taum", stan::model::index_uni(sym1__));
          current_statement__ = 7;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, taum);
      Eigen::Matrix<local_scalar_t__,-1,1> sigt =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(NV, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigt_flat__;
        current_statement__ = 8;
        sigt_flat__ = context__.vals_r("sigt");
        current_statement__ = 8;
        pos__ = 1;
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
          current_statement__ = 8;
          stan::model::assign(sigt, sigt_flat__[(pos__ - 1)],
            "assigning variable sigt", stan::model::index_uni(sym1__));
          current_statement__ = 8;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigt);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 9;
      rho = context__.vals_r("rho")[(1 - 1)];
      out__.write_free_lub(0, 1, rho);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"Omega_local", "Omega_global", "tau",
                "Betas", "BetaM", "BetaS", "taum", "sigt", "rho"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"mu", "Sigs"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    Nstudies),
                                                 static_cast<size_t>(NV),
                                                 static_cast<size_t>(NV)},
                std::vector<size_t>{static_cast<size_t>(NV),
                  static_cast<size_t>(NV)},
                std::vector<size_t>{static_cast<size_t>(Nstudies),
                  static_cast<size_t>(NV)},
                std::vector<size_t>{static_cast<size_t>(Nstudies),
                  static_cast<size_t>(NP), static_cast<size_t>(NV)},
                std::vector<size_t>{static_cast<size_t>(NP),
                  static_cast<size_t>(NV)},
                std::vector<size_t>{static_cast<size_t>(NP),
                  static_cast<size_t>(NV)},
                std::vector<size_t>{static_cast<size_t>(NV)},
                std::vector<size_t>{static_cast<size_t>(NV)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(Nrecords),
               static_cast<size_t>(NV)},
             std::vector<size_t>{static_cast<size_t>(Nstudies),
               static_cast<size_t>(NV), static_cast<size_t>(NV)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= NV; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
          param_names__.emplace_back(std::string() + "Omega_local" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= NV; ++sym2__) {
        param_names__.emplace_back(std::string() + "Omega_global" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= Nstudies; ++sym2__) {
        param_names__.emplace_back(std::string() + "tau" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
          param_names__.emplace_back(std::string() + "Betas" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
        param_names__.emplace_back(std::string() + "BetaM" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
        param_names__.emplace_back(std::string() + "BetaS" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      param_names__.emplace_back(std::string() + "taum" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigt" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= Nrecords; ++sym2__) {
          param_names__.emplace_back(std::string() + "mu" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= NV; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
            param_names__.emplace_back(std::string() + "Sigs" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= ((NV * (NV - 1)) / 2); ++sym1__) {
      for (int sym2__ = 1; sym2__ <= Nstudies; ++sym2__) {
        param_names__.emplace_back(std::string() + "Omega_local" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= ((NV * (NV - 1)) / 2); ++sym1__) {
      param_names__.emplace_back(std::string() + "Omega_global" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= Nstudies; ++sym2__) {
        param_names__.emplace_back(std::string() + "tau" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
          param_names__.emplace_back(std::string() + "Betas" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
        param_names__.emplace_back(std::string() + "BetaM" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= NP; ++sym2__) {
        param_names__.emplace_back(std::string() + "BetaS" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      param_names__.emplace_back(std::string() + "taum" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigt" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "rho");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= Nrecords; ++sym2__) {
          param_names__.emplace_back(std::string() + "mu" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= NV; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= NV; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= Nstudies; ++sym3__) {
            param_names__.emplace_back(std::string() + "Sigs" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"Omega_local\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nstudies) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NV) + ",\"cols\":" + std::to_string(NV) + "}},\"block\":\"parameters\"},{\"name\":\"Omega_global\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NV) + ",\"cols\":" + std::to_string(NV) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nstudies) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(NV) + "}},\"block\":\"parameters\"},{\"name\":\"Betas\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nstudies) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NP) + ",\"cols\":" + std::to_string(NV) + "}},\"block\":\"parameters\"},{\"name\":\"BetaM\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NP) + ",\"cols\":" + std::to_string(NV) + "},\"block\":\"parameters\"},{\"name\":\"BetaS\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NP) + ",\"cols\":" + std::to_string(NV) + "},\"block\":\"parameters\"},{\"name\":\"taum\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(NV) + "},\"block\":\"parameters\"},{\"name\":\"sigt\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(NV) + "},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(Nrecords) + ",\"cols\":" + std::to_string(NV) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Sigs\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nstudies) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NV) + ",\"cols\":" + std::to_string(NV) + "}},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"Omega_local\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nstudies) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(((NV * (NV - 1)) /2)) + "}},\"block\":\"parameters\"},{\"name\":\"Omega_global\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(((NV * (NV - 1)) /2)) + "},\"block\":\"parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nstudies) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(NV) + "}},\"block\":\"parameters\"},{\"name\":\"Betas\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nstudies) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NP) + ",\"cols\":" + std::to_string(NV) + "}},\"block\":\"parameters\"},{\"name\":\"BetaM\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NP) + ",\"cols\":" + std::to_string(NV) + "},\"block\":\"parameters\"},{\"name\":\"BetaS\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NP) + ",\"cols\":" + std::to_string(NV) + "},\"block\":\"parameters\"},{\"name\":\"taum\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(NV) + "},\"block\":\"parameters\"},{\"name\":\"sigt\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(NV) + "},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(Nrecords) + ",\"cols\":" + std::to_string(NV) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Sigs\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(Nstudies) + ",\"element_type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(NV) + ",\"cols\":" + std::to_string(NV) + "}},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((((((Nstudies * NV) * NV) + (NV * NV)) +
      (Nstudies * NV)) + ((Nstudies * NP) * NV)) + (NP * NV)) + (NP * NV)) +
      NV) + NV) + 1);
    const size_t num_transformed = emit_transformed_parameters * (((Nrecords
      * NV) + ((Nstudies * NV) * NV)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((((((Nstudies * NV) * NV) + (NV * NV)) +
      (Nstudies * NV)) + ((Nstudies * NP) * NV)) + (NP * NV)) + (NP * NV)) +
      NV) + NV) + 1);
    const size_t num_transformed = emit_transformed_parameters * (((Nrecords
      * NV) + ((Nstudies * NV) * NV)));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_mvn_inferH_namespace::model_mvn_inferH;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_mvn_inferH_namespace::profiles__;
}
#endif
#endif
